### ISSUE TITLE
 TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by mrek235** [KarchinLab/HotMAPS_2016#1]
We had this problem while `$ make multipleTestCorrect OUTPUT_DIR=output/1e96_output MUPIT_ANNOTATION_DIR=1e96_example/mupit_annotations` using this command from quick start, and we tried to fix it by changing 41st line of statistics.py in src folder to:
`pval_adj = np.zeros(int(n))`
Is this the correct way to do it?

**Comment by ctokheim** [comment]
Thank you for reporting this issue. Your edit is indeed correct, as newer versions of numpy are less tolerant of the input for the `zeros` function. My latest commit on github reflects this addition to the code to avoid this issue with future users.
