### ISSUE TITLE
download issue: mupit_modbase.sql.gz not connecting

### ISSUE THREAD

**Issue by FedericaBrando** [KarchinLab/HotMAPS_2016#6]
Hi, I am interesting in running HotMAPS, although I am having troubles downloading the mupit_modbase db from the url:
http://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz, it gives connection timed out error. 

Is there a new working link where I can retrieve the dataset? Thanks

**Comment by RachelKarchin** [comment]
Use https://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz

**Comment by FedericaBrando** [comment]
Thanks a lot for the reply! Right now I do not get a connection error anymore, rather I have an error because of the certificate expiration:

```sh
wget https://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
--2023-10-20 17:26:37--  https://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
Resolving karchinlab.org (karchinlab.org)... 162.129.223.26
Connecting to karchinlab.org (karchinlab.org)|162.129.223.26|:443... connected.
ERROR: The certificate of ‘karchinlab.org’ is not trusted.
ERROR: The certificate of ‘karchinlab.org’ has expired.
```

**Comment by RachelKarchin** [comment]
Thanks for reporting this. We will get it fixed asap. We also have an updated version of HotMAPS that we haven't released yet, but which is much easier to use. If you are interested, I can share that repo with you.

**Comment by RachelKarchin** [comment]
Does this url work? The cert has not expired so we're trying to figure things out.

https://www.karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz

**Comment by FedericaBrando** [comment]
Hi, I've tested the new link you provide and I still get the error:

```sh
wget https://www.karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
--2023-10-23 10:32:37--  https://www.karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
Resolving www.karchinlab.org (www.karchinlab.org)... 162.129.223.26
Connecting to www.karchinlab.org (www.karchinlab.org)|162.129.223.26|:443... connected.
ERROR: cannot verify www.karchinlab.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to www.karchinlab.org insecurely, use `--no-check-certificate'.
```

The only way to download is by using the flag in the error. 

Regarding the new release of HotMAPs I would be very interested! Thank you :)

**Comment by RachelKarchin** [comment]
We've been unable to reproduce your issue. Using the same command, we do not get the expiration message.  What OS and version are you running?

**Comment by FedericaBrando** [comment]
Indeed, on my local machine I do not have any warnings, on the hpc I'm working although I get the error abovementioned. 

This is the specification of the machine:
```sh
>uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
>lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

```

**Comment by RachelKarchin** [comment]
Debian 8.11 Jessie was End-Of-Lifed June 30, 2020, and likely it
has old CA certificates installed.  If you can find a way to update the
CA certificates on your system that will likely fix this issue, or you
can simply continue using the "--no-check-certificate" flag.  But being
EOL, this is just the beginning of issues you will be facing on that
system...

**Comment by migrau** [comment]
@RachelKarchin Is this file available anywhere else? Thanks! 

```
$  wget http://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
--2024-03-06 15:16:31--  http://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
Resolving karchinlab.org (karchinlab.org)... 162.129.223.26
Connecting to karchinlab.org (karchinlab.org)|162.129.223.26|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz [following]
--2024-03-06 15:16:32--  https://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
Connecting to karchinlab.org (karchinlab.org)|162.129.223.26|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-06 15:16:33 ERROR 404: Not Found.
````

**Comment by RachelKarchin** [comment]
Hi Migrau,

We have a new, improved version of HotMAPs that does not depend on a mysql database and is much easier to use. Please check it out. https://github.com/KarchinLab/HotMAPS

Best
